/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClinicmanagerRouteImport } from './routes/clinicmanager'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as SuperadminLogoutRouteImport } from './routes/superadmin.logout'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as SlugClinicmanagerRouteImport } from './routes/$slug_.clinicmanager'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedSuperadminSecurityRouteImport } from './routes/_authenticated/superadmin.security'
import { Route as AuthenticatedSlugManageRouteImport } from './routes/_authenticated/$slug.manage'
import { Route as SlugDoctorsDoctorIdRouteImport } from './routes/$slug.doctors.$doctorId'
import { Route as ApiPublicHooksSecurityScanRouteImport } from './routes/api/public/hooks/security-scan'
import { Route as ApiPublicHooksEmailExpirySweepRouteImport } from './routes/api/public/hooks/email-expiry-sweep'
import { Route as SlugClinicmanagerDoctorsDoctorIdRouteImport } from './routes/$slug_.clinicmanager.doctors.$doctorId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicmanagerRoute = ClinicmanagerRouteImport.update({
  id: '/clinicmanager',
  path: '/clinicmanager',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLogoutRoute = SuperadminLogoutRouteImport.update({
  id: '/superadmin/logout',
  path: '/superadmin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugClinicmanagerRoute = SlugClinicmanagerRouteImport.update({
  id: '/$slug_/clinicmanager',
  path: '/$slug/clinicmanager',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminSecurityRoute =
  AuthenticatedSuperadminSecurityRouteImport.update({
    id: '/superadmin/security',
    path: '/superadmin/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSlugManageRoute = AuthenticatedSlugManageRouteImport.update({
  id: '/$slug/manage',
  path: '/$slug/manage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugDoctorsDoctorIdRoute = SlugDoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => SlugRoute,
} as any)
const ApiPublicHooksSecurityScanRoute =
  ApiPublicHooksSecurityScanRouteImport.update({
    id: '/api/public/hooks/security-scan',
    path: '/api/public/hooks/security-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailExpirySweepRoute =
  ApiPublicHooksEmailExpirySweepRouteImport.update({
    id: '/api/public/hooks/email-expiry-sweep',
    path: '/api/public/hooks/email-expiry-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugClinicmanagerDoctorsDoctorIdRoute =
  SlugClinicmanagerDoctorsDoctorIdRouteImport.update({
    id: '/doctors/$doctorId',
    path: '/doctors/$doctorId',
    getParentRoute: () => SlugClinicmanagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/clinicmanager': typeof ClinicmanagerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/clinicmanager': typeof SlugClinicmanagerRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/logout': typeof SuperadminLogoutRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/$slug/doctors/$doctorId': typeof SlugDoctorsDoctorIdRoute
  '/$slug/manage': typeof AuthenticatedSlugManageRoute
  '/superadmin/security': typeof AuthenticatedSuperadminSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/$slug/clinicmanager/doctors/$doctorId': typeof SlugClinicmanagerDoctorsDoctorIdRoute
  '/api/public/hooks/email-expiry-sweep': typeof ApiPublicHooksEmailExpirySweepRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/clinicmanager': typeof ClinicmanagerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/clinicmanager': typeof SlugClinicmanagerRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/logout': typeof SuperadminLogoutRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/$slug/doctors/$doctorId': typeof SlugDoctorsDoctorIdRoute
  '/$slug/manage': typeof AuthenticatedSlugManageRoute
  '/superadmin/security': typeof AuthenticatedSuperadminSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/$slug/clinicmanager/doctors/$doctorId': typeof SlugClinicmanagerDoctorsDoctorIdRoute
  '/api/public/hooks/email-expiry-sweep': typeof ApiPublicHooksEmailExpirySweepRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/clinicmanager': typeof ClinicmanagerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug_/clinicmanager': typeof SlugClinicmanagerRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/logout': typeof SuperadminLogoutRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/$slug/doctors/$doctorId': typeof SlugDoctorsDoctorIdRoute
  '/_authenticated/$slug/manage': typeof AuthenticatedSlugManageRoute
  '/_authenticated/superadmin/security': typeof AuthenticatedSuperadminSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/$slug_/clinicmanager/doctors/$doctorId': typeof SlugClinicmanagerDoctorsDoctorIdRoute
  '/api/public/hooks/email-expiry-sweep': typeof ApiPublicHooksEmailExpirySweepRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/clinicmanager'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/clinicmanager'
    | '/app'
    | '/superadmin/login'
    | '/superadmin/logout'
    | '/superadmin/'
    | '/$slug/doctors/$doctorId'
    | '/$slug/manage'
    | '/superadmin/security'
    | '/api/public/health'
    | '/$slug/clinicmanager/doctors/$doctorId'
    | '/api/public/hooks/email-expiry-sweep'
    | '/api/public/hooks/security-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/clinicmanager'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/clinicmanager'
    | '/app'
    | '/superadmin/login'
    | '/superadmin/logout'
    | '/superadmin'
    | '/$slug/doctors/$doctorId'
    | '/$slug/manage'
    | '/superadmin/security'
    | '/api/public/health'
    | '/$slug/clinicmanager/doctors/$doctorId'
    | '/api/public/hooks/email-expiry-sweep'
    | '/api/public/hooks/security-scan'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/clinicmanager'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug_/clinicmanager'
    | '/_authenticated/app'
    | '/superadmin/login'
    | '/superadmin/logout'
    | '/superadmin/'
    | '/$slug/doctors/$doctorId'
    | '/_authenticated/$slug/manage'
    | '/_authenticated/superadmin/security'
    | '/api/public/health'
    | '/$slug_/clinicmanager/doctors/$doctorId'
    | '/api/public/hooks/email-expiry-sweep'
    | '/api/public/hooks/security-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ClinicmanagerRoute: typeof ClinicmanagerRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  SlugClinicmanagerRoute: typeof SlugClinicmanagerRouteWithChildren
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminLogoutRoute: typeof SuperadminLogoutRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksEmailExpirySweepRoute: typeof ApiPublicHooksEmailExpirySweepRoute
  ApiPublicHooksSecurityScanRoute: typeof ApiPublicHooksSecurityScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicmanager': {
      id: '/clinicmanager'
      path: '/clinicmanager'
      fullPath: '/clinicmanager'
      preLoaderRoute: typeof ClinicmanagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/logout': {
      id: '/superadmin/logout'
      path: '/superadmin/logout'
      fullPath: '/superadmin/logout'
      preLoaderRoute: typeof SuperadminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug_/clinicmanager': {
      id: '/$slug_/clinicmanager'
      path: '/$slug/clinicmanager'
      fullPath: '/$slug/clinicmanager'
      preLoaderRoute: typeof SlugClinicmanagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin/security': {
      id: '/_authenticated/superadmin/security'
      path: '/superadmin/security'
      fullPath: '/superadmin/security'
      preLoaderRoute: typeof AuthenticatedSuperadminSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/manage': {
      id: '/_authenticated/$slug/manage'
      path: '/$slug/manage'
      fullPath: '/$slug/manage'
      preLoaderRoute: typeof AuthenticatedSlugManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug/doctors/$doctorId': {
      id: '/$slug/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/$slug/doctors/$doctorId'
      preLoaderRoute: typeof SlugDoctorsDoctorIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/public/hooks/security-scan': {
      id: '/api/public/hooks/security-scan'
      path: '/api/public/hooks/security-scan'
      fullPath: '/api/public/hooks/security-scan'
      preLoaderRoute: typeof ApiPublicHooksSecurityScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-expiry-sweep': {
      id: '/api/public/hooks/email-expiry-sweep'
      path: '/api/public/hooks/email-expiry-sweep'
      fullPath: '/api/public/hooks/email-expiry-sweep'
      preLoaderRoute: typeof ApiPublicHooksEmailExpirySweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug_/clinicmanager/doctors/$doctorId': {
      id: '/$slug_/clinicmanager/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/$slug/clinicmanager/doctors/$doctorId'
      preLoaderRoute: typeof SlugClinicmanagerDoctorsDoctorIdRouteImport
      parentRoute: typeof SlugClinicmanagerRoute
    }
  }
}

interface SlugRouteChildren {
  SlugDoctorsDoctorIdRoute: typeof SlugDoctorsDoctorIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugDoctorsDoctorIdRoute: SlugDoctorsDoctorIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedSlugManageRoute: typeof AuthenticatedSlugManageRoute
  AuthenticatedSuperadminSecurityRoute: typeof AuthenticatedSuperadminSecurityRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedSlugManageRoute: AuthenticatedSlugManageRoute,
  AuthenticatedSuperadminSecurityRoute: AuthenticatedSuperadminSecurityRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SlugClinicmanagerRouteChildren {
  SlugClinicmanagerDoctorsDoctorIdRoute: typeof SlugClinicmanagerDoctorsDoctorIdRoute
}

const SlugClinicmanagerRouteChildren: SlugClinicmanagerRouteChildren = {
  SlugClinicmanagerDoctorsDoctorIdRoute: SlugClinicmanagerDoctorsDoctorIdRoute,
}

const SlugClinicmanagerRouteWithChildren =
  SlugClinicmanagerRoute._addFileChildren(SlugClinicmanagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ClinicmanagerRoute: ClinicmanagerRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  SlugClinicmanagerRoute: SlugClinicmanagerRouteWithChildren,
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminLogoutRoute: SuperadminLogoutRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksEmailExpirySweepRoute: ApiPublicHooksEmailExpirySweepRoute,
  ApiPublicHooksSecurityScanRoute: ApiPublicHooksSecurityScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
